name: AutoPlacePatch
version: '${project.version}'
main: com.quadflame.autoplacepatch.AutoPlacePatch
softdepend:
  - ViaVersion
commands:
  autoplacepatch:
    description: Main command for AutoPlacePatch
    permission: autoplacepatch.command
    aliases:
    - app

permissions:
  autoplacepatch.command:
    description: Allows use of /autoplacepatch command
    default: op
  autoplacepatch.bypass:
    description: Bypasses all auto-place checks
    default: op