name: AutoPlacePatch
version: '${project.version}'
main: com.quadflame.autoplacepatch.AutoPlacePatch
description: A plugin to detect AutoPlace hacks
author: quadflame
website: https://github.com/quadflame/AutoPlacePatch
softdepend:
  - ViaVersion
commands:
  autoplacepatch:
    description: Main command for AutoPlacePatch
    aliases:
    - app

permissions:
  autoplacepatch.reload:
    description: Allows use of /autoplacepatch reload
    default: op
  autoplacepatch.bypass:
    description: Bypasses all auto-place checks
    default: op
  autoplacepatch.alerts:
    description: Allows receiving and toggling alerts for auto-place violations
    default: op